routes/web.php
	Route::get('skipreasons/delete/{id}', 'SkipReasonController@destroy');
	Route::get('routes/delete/{id}', 'RouteController@destroy');
	Route::get('departments/delete/{id}', 'DepartmentController@destroy');
	Route::get('instruments/delete/{id}', 'InstrumentController@destroy');
	Route::get('units/delete/{id}', 'UnitController@destroy');
	Route::get('plantstatus/delete/{id}', 'PlantStatusController@destroy');
	Route::get('linestatus/delete/{id}', 'LineStatusController@destroy');
	Route::get('lines/delete/{id}', 'LineController@destroy');
	Route::get('assetstatus/delete/{id}', 'AssetStatusController@destroy');
	Route::get('tools/delete/{id}', 'ToolController@destroy');
	Route::get('assets/delete/{id}', 'AssetController@destroy');
	Route::get('parameters/delete/{id}', 'ParameterController@destroy');
	Route::get('deviations/delete/{id}', 'DeviationController@destroy');
	Route::get('departmentdashboard', 'DepartmentController@getDepartmentDashoard');
	Route::get('linedashboard', 'LineController@getLineDashoard');
	Route::get('assetdashboard', 'AssetController@getAssetDashoard');
	Route::get('instrumentdashboard', 'InstrumentController@getInstrumentDashoard');
	Route::get('parameterdashboard', 'ParameterController@getParameterDashoard');
	Route::get('plantadmin/delete/{id}', 'PlantAdminController@destroy');
	Route::get('unitstatus/delete/{id}', 'UnitStatusController@destroy');
	Route::get('departmentstatus/delete/{id}', 'DepartmentStatusController@destroy');
	Route::get('instrumentstatus/delete/{id}', 'InstrumentStatusController@destroy');
	Route::get('toolstatus/delete/{id}', 'ToolStatusController@destroy');
	Route::get('calculateworkorder','WorkOrderController@calculateWorkOrderPercentages');
	Route::get('opendetailworkorder','DashboardController2@openDetail')->name('workorders.opendetail');
	Route::get('closedetailworkorder','DashboardController2@closeDetail')->name('workorders.closedetail');
	Route::get('openackworkorder','DashboardController2@ackDetail')->name('workorders.openack');

	Route::get('openunackworkorder','DashboardController2@unAckDetail')->name('workorders.openunack');
	Route::get('routeinprogress','DashboardController@detailInProgressRoute')->name('routes.inprogress');
	Route::get('routecomplete','DashboardController@detailRouteComplete')->name('routes.complete');
	Route::get('routecancle','DashboardController@detailRouteCancle')->name('routes.cancle');
	Route::get('routedelay','DashboardController@detailRouteDelayed')->name('routes.delay');
	Route::get('totalalarms','DashboardController@detailTotalAlarm')->name('alarms.total');
	Route::get('currentalarms','DashboardController@detailCurrentAlarm')->name('alarms.current');
	Route::get('ackalarm','DashboardController@detailAckAlarm')->name('alarms.ackalarm');
	Route::get('unackalarm','DashboardController@detailUnAckAlarm')->name('alarms.unackalarm');

	Route::get('/authenticationerror',function()
	{
	    return view('authentication_error');
	});
	//All qrcodes print 
	Route::get('qr-code', 'InstrumentController@selectInstrument')->name('qr-code.selectinstrument');
	Route::post('printallqr', 'QrcodeController@printAllQr');
	
	Route::get('admin/pages',function()
	{
	    return view('undercontruction.index');
	});
	Route::get('/parametervalues', 'ParameterController@parameterValues')->name('parametervalues.index');

	Route::get('/munualdataentry',function()
	{
	    return view('manualdataentry.index');
	});

	Route::post('/parameter/manualdataentrystore', 'ParameterController@manualdataentry')->name('manualdataentrystore');
	Route::get('/instrumentworkorderform', 'WorkOrderController@instrumentWorkOrder');
	Route::post('/storeinstrumentworkorder', 'WorkOrderController@storeinstrumentWorkOrder')->name('workorders.storeinstrumentworkorder');

	Route::get('/showinspectionpoints/align/{id}', 'RouteController@RouteAlignCreate')->name('showinspectionpoints.align');

	Route::get('/slip', 'QrcodeController@slip');
	Route::get('/slip2', 'QrcodeController@slip2');
	Route::get('/slip3', 'QrcodeController@slip3');
	Route::get('/slip4', 'QrcodeController@slip4');
	Route::get('/slip5', 'QrcodeController@slip5');
	Route::get('multipleanalytics',function()
	{
	    return view('analytics.multiple-analytics');
	});
	Route::get('singleanalytics',function()
	{
	    return view('analytics.single-analytics');
	});
	
	Route::get('/slip', 'QrcodeController@slip');
	Route::get('/slip2', 'QrcodeController@slip2');
	Route::get('/slip3', 'QrcodeController@slip3');
	Route::get('/slip4', 'QrcodeController@slip4');
	Route::get('/slip5', 'QrcodeController@slip5');
	Route::get('multipleanalytics',function()
	{
	    return view('analytics.multiple-analytics');
	});
	Route::get('routeskippedinstruments/{id}','RouteHistoryController@getSkippedInstrument'); 
	
	Route::get('showinspectionpoint/{id}','RouteController@showInspectionPoint');
	Route::get('showinspectionperemeter/{id}','RouteController@showInspectionParameter')->name('showinspectionperemeter'); 

	Route::get('showunitdepartment/{id}','DepartmentController@showUnitDepartment')->name('showunitdepartment');
	Route::get('showdepartmentline/{id}','LineController@showDepartmentLine')->name('showdepartmentline');
	Route::get('showlineasset/{id}','AssetController@showLineAsset')->name('showlineasset');
	Route::get('showassetinstrument/{id}','InstrumentController@showAssetInstrument')->name('showassetinstrument');
	Route::get('showinstrumentparameter/{id}','ParameterController@showInstrumentParameter')->name('showinstrumentparameter');


	Route::get('acknowledgeworkorder','WorkOrderController@acknowledgeWorkOrder');
	Route::get('getspecificunitdepartment/departments',function()
	{
	    return view('departments.index');
	});
	Route::get('singleanalytics',function()
	{
	    return view('analytics.single-analytics');
	});
	Route::get('/home', 'DashboardController@index')->name('home');
	Route::get('/', 'DashboardController@index');
	Route::get('dashboardview', 'DashboardController@index');
	Route::get('/showparameteranalytics/{id}', 'ParameterController@showSelectedParameterAnalytics')->name('showanalytics');

	Route::group(['middleware' => ['can:tree_dashboard-index']], function () {
	    		
		    Route::get('unitdashboard', 'UnitController@getUnitDashoard');
		    Route::get('getspecificunitdepartment/{id}','DepartmentController@getDepartmentDashoard')->name('get_unit_department');

			Route::get('getspecificdepartmentline/{id}','LineController@getLineDashoard')->name('get_department_line');
			Route::get('getspecificlineasset/{id}','AssetController@getAssetDashoard')->name('get_line_asset');
			Route::get('getspecificassetinstrument/{id}','InstrumentController@getInstrumentDashoard')->name('get_asset_instrument');
			// Route::get('getspecificparameter/{id}','InstrumentController@getInstrumentDashoard')->name('get_asset_instrument');

			Route::get('getspecificinstrumentparameter/{id}','ParameterController@getParameterDashoard')->name('get_instrument_parameter'); 
			Route::get('getunitdetaildata/{id}','ParameterController@getUnitDetailData')->name('get_unit_detail_data');
			Route::get('getdepartmentdetaildata/{id}','ParameterController@getDepartmentDetailData')->name('get_department_detail_data');
			Route::get('getlinedetaildata/{id}','ParameterController@getLineDetailData')->name('get_line_detail_data');
			Route::get('getassetdetaildata/{id}','ParameterController@getAssetDetailData')->name('get_asset_detail_data');
			Route::get('getinstrumentdetaildata/{id}','ParameterController@getInstrumentDetailData')->name('get_instrument_detail_data');
			Route::post('/storeinstrumentworkorder', 'WorkOrderController@storeinstrumentWorkOrder')->name('workorders.storeinstrumentworkorder'); 
				});
		Route::group(['middleware' => ['can:workorderdashboard-index']], function () {
    		Route::get('workorderdashboard', 'DashboardController2@index');
			Route::resource('workorderhistory','WorkOrderHistoryController');
			Route::resource('currentworkorder','CurrentWorkOrderController');
			Route::get('workorders/delete/{id}', 'WorkOrderController@destroy');
			Route::get('currentworkorder/check_acknowledgement','WorkOrderController@checkAcknowledgement')->name('check_acknowledgement');
			Route::resource('workorders','WorkOrderController');
	    	Route::resource('users','UserController');

			Route::get('workorderdetails', 'DashboardController2@workOrderDetail')->name('workorderdetail');
	    	Route::resource('routes','RouteController');
	    	Route::resource('routehistory','RouteHistoryController');
	    	Route::get('/currentworkorder/ackwork/{id}', 'WorkOrderController@ackIndividualWorkorder');
			});

		Route::group(['middleware' => ['can:plant_admin_alarm_dashboard-index']], function () {

		Route::get('alarmdashboard', 'DashboardController2@alarmDashboard');
		Route::get('allunits', 'UnitController@allUnits')->name('allunits');
		Route::get('alldepartments', 'DepartmentController@allDepartments')->name('alldepartments');
		Route::get('alllines', 'LineController@allLines')->name('alllines');
		Route::get('allassets', 'AssetController@allAssets')->name('allassets');
		Route::get('allinstruments', 'InstrumentController@allInstruments')->name('allinstruments');
		Route::get('allparameters', 'ParameterController@allParameters')->name('allparameters');
	    Route::resource('alarms','AlarmController'); 
	    Route::get('alarms/delete/{id}', 'AlarmController@destroy'); 
	    Route::get('/currentalarmstate', 'AlarmController@currentAlarmState')->name('alarms.currentAlarmState');
		Route::get('/alarmhistory', 'AlarmController@alarmHistory')->name('alarms.alarmHistory');
		Route::get('/acknowledge', 'AlarmController@acknowledge');
		Route::get('/acknowledgecurrentalarms', 'AlarmController@acknowledgeCurrentAlarms');
		Route::get('/currentalarmstate/ack/{id}', 'AlarmController@ackIndividualAlarm');
		Route::get('/groups/add/{id}', 'GroupController@addUser');
		// Route::get('contacts/delete/{id}', 'ContactController@destroy');
		//Report

app/Http/Controllers/WorkOrderHistoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Kris\LaravelFormBuilder\FormBuilder;
use App\Forms\DepartmentForm;
use App\Http\Controllers\Controller;
//use App\Http\Controllers\Plant;
use App\Model\WorkOrderHistory;
use App\Model\WorkOrder;
use App\Post;
use App\User;
use Auth;
use Yajra\Datatables\Datatables;
use DB;
use Response;
Use Exception;
use Hash;
use Helper;

class WorkOrderHistoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:workorder-history-index', ['only' => ['index','store']]);

        return view('permission-error');
    }
    public function index(Request $request)
    {                  
        if($request->ajax())
        {
            $workorderhistory = DB::table('workorder_history')
                ->join('current_workorder', 'workorder_history.current_workorder_id', '=', 'current_workorder.id')
                ->select('workorder_history.*', 'current_workorder.workorder_id','current_workorder.priority','current_workorder.acknowledgement');
            
            $workorder_complete = DB::table('workorders')
                ->joinSub($workorderhistory, 'current_workorder', function ($join) {
                $join->on('workorders.id', '=', 'current_workorder.workorder_id');
            })->get();

                
            $workorder_history = [];

            foreach ($workorder_complete as $key => $data) {
                $w_h = (array)$data;
                $w_h['remarks'] = Helper::workorderIdToRemarks($w_h['current_workorder_id']);
                $w_h['instrument_id'] = Helper::instrumentIdToName($w_h['instrument_id']);
                $w_h['action_taken_by'] = Helper::userIdToName($w_h['action_taken_by']);
                array_push($workorder_history, $w_h);
            }
            return Datatables::of($workorder_history)
                ->setRowClass('@if($priority=="high") 
                    {{ "alert-danger" }} 
                    @elseif($priority=="medium")
                    {{"alert-warning"}}
                    @endif 
                    ')
                ->make(true);
        }    
        return view('workorderhistory.index');            
    }

}

resources/views/workorderhistory/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
  <div class="row">
    <div class="col-md-6">
      <h1 style="margin-bottom:0px;"><b>Workorder History</b></h1>    
    </div>
    <div class="col-md-6">   
      <label class="dropdown" style="float: right; margin-right: 5px;">
        <div class="dd-button">
          Manage  
        </div>    
        <input type="checkbox" class="dd-input" id="test">
          <ul class="dd-menu">

           <a class="btn btn-success" style="width :100%;padding: 6%; background-color:#1a1c33;"href="/workorderdashboard"><li style="color: white"><i class="fas fa-chalkboard-teacher"></i>  &nbsp; Dashboard </li></a> 
           <li class="divide"></li>

           <a class="btn btn-success" style="width :100%; padding: 5%; background-color: #1a1c33;"href="{{ route('currentworkorder.index') }}"><li style="color: white"><i class="fas fa-wallet"></i>  &nbsp;Current </li></a> 
           <li class="divide"></li>

           <a class="btn btn-success" style="width :100%;padding: 5%; background-color: #1a1c33;" href="{{ route('workorders.index') }}"><li style="color: white"><i class="fas fa-cog"></i>  &nbsp; Setting </li></a>       
        </ul>
      </label>       
    </div>
  </div>
    <hr class="divider">
@stop
 
@section('content')
<div class="centered-container">
  <div class="row">
    <div class="col-md-9">
    </div>
    <div class="col-md-3">
    </div>
  </div>

  @if ($message = Session::get('success'))
  <div class="alert alert-success">
    <p>{{ $message }}</p>
  </div>
  @endif

  @yield('datatable', View::make('datatables.workorderhistory-datatable'))
</div>
@stop
@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
<link rel="stylesheet" href="bower_components/chart.js/dist/Chart.min.css">

@stop


@section('plugins.Datatables', true)
<style type="text/css">

a:hover {
  color: red;
}

/* Dropdown */

.dropdown {
  display: inline-block;
  position: relative;
  z-index: 1;
}

.dd-button {
  display: inline-block;
  border: 1px solid gray;
  border-radius: 4px;
  padding: 10px 30px 10px 20px;
  background-color: #1a1c33;
  cursor: pointer;
  white-space: nowrap;
  color: white;
}

.dd-button:after {
  content: '';
  position: absolute;
  top: 50%;
  right: 15px;
  transform: translateY(-50%);
  width: 0; 
  height: 0; 
  border-left: 5px solid transparent;
  border-right: 5px solid transparent;
  border-top: 5px solid white;
  z-index: 1;
}

.dd-button:hover {
  background-color: #6d728a;
}


.dd-input {
  display: none;
}

.dd-menu {
  position: absolute;
  top: 100%;
  border: 1px solid #ccc;
  border-radius: 4px;
  padding: 0;
  margin: 2px 0 0 0;
  box-shadow: 0 0 6px 0 rgba(0,0,0,0.1);
  background-color: pink;
  list-style-type: none;
  color: white;
  z-index: 1;
}

.dd-input + .dd-menu {
  display: none;
  z-index: 1;
} 

.dd-input:checked + .dd-menu {
  display: block;
} 

.dd-menu li {
  padding: 10px 20px;
  cursor: pointer;
  white-space: nowrap;
  z-index: 1;
}
.dd-button::after{
  border-top: 5px solid white;
}

.dd-menu li:hover {
  background-color: #007bff;
}

.dd-menu li a {
  display: block;
  margin: -10px -20px;
  padding: 10px 20px;
  z-index: 1;
}

.dd-menu li.divide{
  padding: 0;
  border-bottom: 1px solid #fcf9fe;
}
</style>
@section('js')
  
@stop