routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// // analytics route
// Route::get('/analytics-single','SingleParameterController@create');

Route::get('singleparameter','AnalyticsController@singleParameter');
// Route::get('getroutetools', 'RouteController@getRouteTools');
Route::get('getroutetoolsdata', 'RouteController@getRouteToolsData');

// Route::get('test', 'WorkOrderController@test');
Route::get('/assetmodal',function()
{
    return view('dashboardtree.asset');
});


// Route::get('/findparameter', 'SingleParameterController@findparameter');
// Route::get('/intrumentParameter', 'SingleParameterController@intrumentParameter');
// Route::get("analytics/analytics-single-parameter", 'SingleParameterController@index')->name("analytics.analytics-single-parameter");



Auth::routes();


Route::group(['middleware' => ['auth']], function() 
{
	Route::get('logout','Auth\LoginController@logout')->name('logout');
	Route::resource('roles','RoleController');	
	Route::resource('plants','PlantController');
	Route::resource('departments','DepartmentController');
	Route::resource('lines','LineController');
	Route::resource('assets','AssetController');
	Route::resource('assetstatus','AssetStatusController');
	
	Route::resource('status','StatusController');
	Route::get('status/delete/{id}', 'StatusController@destroy');
	
	Route::resource('instruments','InstrumentController');
	Route::resource('tools','ToolController');
	Route::resource('plantstatus','PlantStatusController');
	Route::resource('unitstatus','UnitStatusController');
	Route::resource('departmentstatus','DepartmentStatusController');
	Route::resource('instrumentstatus','InstrumentStatusController');
	Route::resource('toolstatus','ToolStatusController');
	Route::resource('instrumentworkorder','InstrumentWorkOrderController');
	Route::resource('linestatus','LineStatusController');
	Route::resource('parameters','ParameterController');
	Route::resource('qrcodes','QrcodeController');
	Route::resource('deviations','DeviationController');
	Route::resource('permissions','PermissionController');
	Route::resource('skipreasons','SkipReasonController');
	Route::resource('units','UnitController');
	Route::resource('groups','GroupController');  
	Route::resource('registerroute','RegisterRouteController');

	Route::get('routes/show-skipreasonsinstrument-point/{id}','RouteInstrumentController@index');
	
	//clicking on add icon in inspection points
	Route::get('addparamtoinspectionpoint/{id}','RouteController@addParamCreate')->name('addparamtoinspectionpoint');

	Route::resource('plantadmin','PlantAdminController');
	Route::get('/findparameter', 'RouteController@findparameter');
	Route::get('instrumentworkorder/delete/{id}', 'InstrumentWorkOrderController@destroy');
	Route::get('users/delete/{id}', 'UserController@destroy');
	Route::get('roles/delete/{id}', 'RoleController@destroy');
	Route::get('permissions/delete/{id}', 'PermissionController@destroy');
	Route::get('plants/delete/{id}', 'PlantController@destroy');
	Route::get('skipreasons/delete/{id}', 'SkipReasonController@destroy');
	Route::get('routes/delete/{id}', 'RouteController@destroy');
	Route::get('departments/delete/{id}', 'DepartmentController@destroy');
	Route::get('instruments/delete/{id}', 'InstrumentController@destroy');
	Route::get('units/delete/{id}', 'UnitController@destroy');
	Route::get('plantstatus/delete/{id}', 'PlantStatusController@destroy');
	Route::get('linestatus/delete/{id}', 'LineStatusController@destroy');
	Route::get('lines/delete/{id}', 'LineController@destroy');
	Route::get('assetstatus/delete/{id}', 'AssetStatusController@destroy');
	Route::get('tools/delete/{id}', 'ToolController@destroy');
	Route::get('assets/delete/{id}', 'AssetController@destroy');
	Route::get('parameters/delete/{id}', 'ParameterController@destroy');
	Route::get('deviations/delete/{id}', 'DeviationController@destroy');
	Route::get('departmentdashboard', 'DepartmentController@getDepartmentDashoard');
	Route::get('linedashboard', 'LineController@getLineDashoard');
	Route::get('assetdashboard', 'AssetController@getAssetDashoard');
	Route::get('instrumentdashboard', 'InstrumentController@getInstrumentDashoard');
	Route::get('parameterdashboard', 'ParameterController@getParameterDashoard');
	Route::get('plantadmin/delete/{id}', 'PlantAdminController@destroy');
	Route::get('unitstatus/delete/{id}', 'UnitStatusController@destroy');
	Route::get('departmentstatus/delete/{id}', 'DepartmentStatusController@destroy');
	Route::get('instrumentstatus/delete/{id}', 'InstrumentStatusController@destroy');
	Route::get('toolstatus/delete/{id}', 'ToolStatusController@destroy');
	Route::get('calculateworkorder','WorkOrderController@calculateWorkOrderPercentages');
	Route::get('opendetailworkorder','DashboardController2@openDetail')->name('workorders.opendetail');
	Route::get('closedetailworkorder','DashboardController2@closeDetail')->name('workorders.closedetail');
	Route::get('openackworkorder','DashboardController2@ackDetail')->name('workorders.openack');

	Route::get('openunackworkorder','DashboardController2@unAckDetail')->name('workorders.openunack');
	Route::get('routeinprogress','DashboardController@detailInProgressRoute')->name('routes.inprogress');
	Route::get('routecomplete','DashboardController@detailRouteComplete')->name('routes.complete');
	Route::get('routecancle','DashboardController@detailRouteCancle')->name('routes.cancle');
	Route::get('routedelay','DashboardController@detailRouteDelayed')->name('routes.delay');
	Route::get('totalalarms','DashboardController@detailTotalAlarm')->name('alarms.total');
	Route::get('currentalarms','DashboardController@detailCurrentAlarm')->name('alarms.current');
	Route::get('ackalarm','DashboardController@detailAckAlarm')->name('alarms.ackalarm');
	Route::get('unackalarm','DashboardController@detailUnAckAlarm')->name('alarms.unackalarm');

	Route::get('/authenticationerror',function()
	{
	    return view('authentication_error');
	});
	//All qrcodes print 
	Route::get('qr-code', 'InstrumentController@selectInstrument')->name('qr-code.selectinstrument');
	Route::post('printallqr', 'QrcodeController@printAllQr');
	
	Route::get('admin/pages',function()
	{
	    return view('undercontruction.index');
	});
	Route::get('/parametervalues', 'ParameterController@parameterValues')->name('parametervalues.index');

	Route::get('/munualdataentry',function()
	{
	    return view('manualdataentry.index');
	});

	Route::post('/parameter/manualdataentrystore', 'ParameterController@manualdataentry')->name('manualdataentrystore');
	Route::get('/instrumentworkorderform', 'WorkOrderController@instrumentWorkOrder');
	Route::post('/storeinstrumentworkorder', 'WorkOrderController@storeinstrumentWorkOrder')->name('workorders.storeinstrumentworkorder');

	Route::get('/showinspectionpoints/align/{id}', 'RouteController@RouteAlignCreate')->name('showinspectionpoints.align');

	Route::get('/slip', 'QrcodeController@slip');
	Route::get('/slip2', 'QrcodeController@slip2');
	Route::get('/slip3', 'QrcodeController@slip3');
	Route::get('/slip4', 'QrcodeController@slip4');
	Route::get('/slip5', 'QrcodeController@slip5');
	Route::get('multipleanalytics',function()
	{
	    return view('analytics.multiple-analytics');
	});
	Route::get('singleanalytics',function()
	{
	    return view('analytics.single-analytics');
	});
	
	Route::get('/slip', 'QrcodeController@slip');
	Route::get('/slip2', 'QrcodeController@slip2');
	Route::get('/slip3', 'QrcodeController@slip3');
	Route::get('/slip4', 'QrcodeController@slip4');
	Route::get('/slip5', 'QrcodeController@slip5');
	Route::get('multipleanalytics',function()
	{
	    return view('analytics.multiple-analytics');
	});
	Route::get('routeskippedinstruments/{id}','RouteHistoryController@getSkippedInstrument'); 
	
	Route::get('showinspectionpoint/{id}','RouteController@showInspectionPoint');
	Route::get('showinspectionperemeter/{id}','RouteController@showInspectionParameter')->name('showinspectionperemeter'); 

	Route::get('showunitdepartment/{id}','DepartmentController@showUnitDepartment')->name('showunitdepartment');
	Route::get('showdepartmentline/{id}','LineController@showDepartmentLine')->name('showdepartmentline');
	Route::get('showlineasset/{id}','AssetController@showLineAsset')->name('showlineasset');
	Route::get('showassetinstrument/{id}','InstrumentController@showAssetInstrument')->name('showassetinstrument');
	Route::get('showinstrumentparameter/{id}','ParameterController@showInstrumentParameter')->name('showinstrumentparameter');


	Route::get('acknowledgeworkorder','WorkOrderController@acknowledgeWorkOrder');
	Route::get('getspecificunitdepartment/departments',function()
	{
	    return view('departments.index');
	});
	Route::get('singleanalytics',function()
	{
	    return view('analytics.single-analytics');
	});
	Route::get('/home', 'DashboardController@index')->name('home');
	Route::get('/', 'DashboardController@index');
	Route::get('dashboardview', 'DashboardController@index');
	Route::get('/showparameteranalytics/{id}', 'ParameterController@showSelectedParameterAnalytics')->name('showanalytics');

	Route::group(['middleware' => ['can:tree_dashboard-index']], function () {
	    		
		    Route::get('unitdashboard', 'UnitController@getUnitDashoard');
		    Route::get('getspecificunitdepartment/{id}','DepartmentController@getDepartmentDashoard')->name('get_unit_department');

			Route::get('getspecificdepartmentline/{id}','LineController@getLineDashoard')->name('get_department_line');
			Route::get('getspecificlineasset/{id}','AssetController@getAssetDashoard')->name('get_line_asset');

resources/views/datatables/asset-status-datatable.blade.php
@section('datatable')
<div class="alert alert-success" style="display:none; width: 70%; text-align: center;" id="confirm_delete" role="alert"  >Asset status successfully deleted</div>

<div class="alert alert-warning" style="display:none; width: 70%; text-align: center;" id="foriegn_key_constraint" role="alert"  >Can not delete Asset Status . This Asset  Status is already in use</div><table  class="table table-bordered table-striped table-condensed assetstatus-table" style="width: 100%">
    <thead>
         <tr>
            <th>Asset Name</th>
            <th>Status Name</th>
            <th>Timestamp</th>
            <th style="width: 9%">Action</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
@show

@section('css')

<link rel="stylesheet" type="text/css" href="{{ asset('vendor/datatables/css/dataTables.bootstrap4.min.css') }}">

@stop

@section('js')

<script type="text/javascript" src="{{ asset('vendor/datatables/js/dataTables.bootstrap4.min.js') }}"></script>

<script>
    var table = $('.assetstatus-table').DataTable({
        processing: true,
        serverSide: true,
        scrollX: false,
        order: [ [2, 'desc'] ],
        ajax: "{{ route('assetstatus.index') }}",
        columns: [
            {
             data: 'asset_id',
             name: 'asset_id'
            },
            {
             data: 'status_id', 
             name: 'status_id'
            },
            {data: 'created_at', name: 'created_at'},
            {data: 'action', name: 'action',  orderable: false, searchable: false},
        ]
    });
            var SITEURL = window.location+"/";

    // var SITEURL = '{{URL::to("http://localhost/cbm/public/")}}';

     $(document).ready( function () {
        $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
        });


        $('body').on('click', '#delete', function () {
            var assetstatus_id = $(this).data("id");
           if (confirm("Are You sure want to delete this Asset Status into the Database !")) {
                $.ajax({
                type: "get",
                url: SITEURL + "delete/"+assetstatus_id,
                success: function (data) {
                var oTable = $('.assetstatus-table').dataTable(); 
                oTable.fnDraw(false);
                $('#confirm_delete').show();
                $('#confirm_delete').fadeOut(5000,"swing");
                },
                error: function (data) {
                    console.log('Error:', data);
                    $('#foriegn_key_constraint').show();
                    $('#foriegn_key_constraint').fadeOut(5000,"swing");
                                }
                });
            } else {
               alert("Pagal hai phr delete pe click kue kiya tha ");
            }

        });
    
     });

    function showFunction(id)
    {
        //console.log("click : "+id)
        var url = SITEURL+id;
        window.open(url,'_self');
    }
    
    function editFunction(id)
    {
        //console.log("click : "+id)
        var url = SITEURL+id;
        window.open(url+"/edit",'_self');
    }
</script>
@stop

resources/views/datatables/current-alarm-button.blade.php
<div class="row">
	<div class="col-md-3">
	@if($ack_state=='unacknowledged')								
		<a href="javascript:void(0)" data-toggle="tooltip"  data-id="{{ $id }}" data-original-title="ack-individual-alarm" class="ack-individual-alarm"  onclick="ackIndividualAlarm(<?php echo($id) ?>);">
		<button class="btn btn-success" style="background-color: #1a1c33; margin-right:10px">Acknowledge</button>
		</a>
	@else
	@endif	
	</div>
</div>

 

resources/views/datatables/instrument-fault-datatable.blade.php
@section('datatable')
<div class="alert alert-success" style="display:none; width: 70%; text-align: center;" id="confirm_delete" role="alert"  >Instrument Fault successfully deleted</div>

<div class="alert alert-warning" style="display:none; width: 70%; text-align: center;" id="foriegn_key_constraint" role="alert"  >Can not delete worked againts this instrument . This this workorder_instrumetn id is already in use</div><table  class="table table-bordered table-striped table-condensed instrumentfault-table" style="width: 100%">
    <thead>
         <tr>
            <th>Instrument Name</th>
            <th>Workorder Name</th>
            <th>Timestamp</th>
            <th style="width: 9%">Action</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
@show

@section('css')

<link rel="stylesheet" type="text/css" href="{{ asset('vendor/datatables/css/dataTables.bootstrap4.min.css') }}">

@stop

@section('js')

<script type="text/javascript" src="{{ asset('vendor/datatables/js/dataTables.bootstrap4.min.js') }}"></script>

<script>
    var table = $('.instrumentworkorder-table').DataTable({
        processing: true,
        serverSide: true,
        scrollX: false,
        order: [ [2, 'desc'] ],
        ajax: "{{ route('instrumentworkorder.index') }}",
        columns: [
            {
             data: 'instrument_id',
             name: 'instrument_id'
            },
            {
             data: 'workorder_id', 
             name: 'workorder_id'
            },
            {data: 'created_at', name: 'created_at'},
            {data: 'action', name: 'action',  orderable: false, searchable: false},
        ]
    });
            var SITEURL = window.location+"/";

    // var SITEURL = '{{URL::to("http://localhost/cbm/public/")}}';

     $(document).ready( function () {
        $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
        });


        $('body').on('click', '#delete', function () {
            var instrumentfault_id = $(this).data("id");
           if (confirm("Are You sure want to delete this workorder against instrument?")) {
                $.ajax({
                type: "get",
                url: SITEURL + "delete/"+instrumentfault_id,
                success: function (data) {
                var oTable = $('.instrumentworkorder-table').dataTable(); 
                oTable.fnDraw(false);
                $('#confirm_delete').show();
                $('#confirm_delete').fadeOut(5000,"swing");
                },
                error: function (data) {
                    console.log('Error:', data);
                    $('#foriegn_key_constraint').show();
                    $('#foriegn_key_constraint').fadeOut(5000,"swing");
                                }
                });
            } else {
               alert("Pagal hai phr delete pe click kue kiya tha ");
            }

        });
    
     });

    function showFunction(id)
    {
        //console.log("click : "+id)
        var url = SITEURL+id;
        window.open(url,'_self');
    }
    
    function editFunction(id)
    {
        //console.log("click : "+id)
        var url = SITEURL+id;
        window.open(url+"/edit",'_self');
    }
</script>
@stop

resources/views/datatables/line-status-datatable.blade.php
@section('datatable')
<div class="alert alert-success" style="display:none; width: 70%; text-align: center;" id="confirm_delete" role="alert"  >Line status successfully deleted</div>

<div class="alert alert-warning" style="display:none; width: 70%; text-align: center;" id="foriegn_key_constraint" role="alert"  >Can not delete Line Status . This Line  Status is already in use</div><table  class="table table-bordered table-striped table-condensed linestatus-table" style="width: 100%">
    <thead>
         <tr>
            <th>Line Name</th>
            <th>Status Name</th>
            <th>Timestamp</th>
            <th style="width: 9%">Action</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
@show

@section('css')

<link rel="stylesheet" type="text/css" href="{{ asset('vendor/datatables/css/dataTables.bootstrap4.min.css') }}">

@stop

@section('js')

<script type="text/javascript" src="{{ asset('vendor/datatables/js/dataTables.bootstrap4.min.js') }}"></script>

<script>
    var table = $('.linestatus-table').DataTable({
        processing: true,
        serverSide: true,
        scrollX: false,
        order: [ [2, 'desc'] ],
        ajax: "{{ route('linestatus.index') }}",
        columns: [
            {
             data: 'line_id',
             name: 'line_id'
            },
            {
             data: 'status_id', 
             name: 'status_id'
            },
            {data: 'created_at', name: 'created_at'},
            {data: 'action', name: 'action',  orderable: false, searchable: false},
        ]
    });
            var SITEURL = window.location+"/";

    // var SITEURL = '{{URL::to("http://localhost/cbm/public/")}}';

     $(document).ready( function () {
        $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
        });


        $('body').on('click', '#delete', function () {
            var linestatus_id = $(this).data("id");
           if (confirm("Are You sure want to delete this Line Status into the Database !")) {
                $.ajax({
                type: "get",
                url: SITEURL + "delete/"+linestatus_id,
                success: function (data) {
                var oTable = $('.linestatus-table').dataTable(); 
                oTable.fnDraw(false);
                $('#confirm_delete').show();
                $('#confirm_delete').fadeOut(5000,"swing");
                },
                error: function (data) {
                    console.log('Error:', data);
                    $('#foriegn_key_constraint').show();
                    $('#foriegn_key_constraint').fadeOut(5000,"swing");
                                }
                });
            } else {
               alert("Pagal hai phr delete pe click kue kiya tha ");
            }

        });
    
     });

    function showFunction(id)
    {
        //console.log("click : "+id)
        var url = SITEURL+id;
        window.open(url,'_self');
    }
    
    function editFunction(id)
    {
        //console.log("click : "+id)
        var url = SITEURL+id;
        window.open(url+"/edit",'_self');
    }
</script>
@stop

resources/views/datatables/parameter-datatable.blade.php
  @section('datatable')
<center>
<div class="alert alert-success" style="display:none; width: 70%; text-align: center;" id="confirm_delete" role="alert"  >Parameter successfully deleted</div>

<div class="alert alert-warning" style="display:none; width: 70%; text-align: center;" id="foriegn_key_constraint" role="alert"  >Can not delete parameter. This parameter is already in use</div>

</center>
<table  class="table table-bordered table-striped table-condensed parameters-table" style="width: 100%">
    <thead>
          <tr>
            <th>Parameter Name</th>
            <th>Instrument Name</th>
            <th>Tool Name</th>   
            <th>Description</th>
            <th>Type </th>
            <th>Entry</th>
            <th>Max Value</th>
            <th>Min Value</th>
            <th>EU</th>
            <th>Timestamp</th>
            <th style="width: 9%">Action</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
@show

@section('css')

<link rel="stylesheet" type="text/css" href="{{ asset('vendor/datatables/css/dataTables.bootstrap4.min.css') }}">

@stop

@section('js')

<script type="text/javascript" src="{{ asset('vendor/datatables/js/dataTables.bootstrap4.min.js') }}"></script>

<script>
    var table = $('.parameters-table').DataTable({
        processing: true,
        serverSide: true,
        scrollX: false,
        order: [ [9, 'desc'] ],
        ajax: "{{ route('parameters.index') }}",
        columns: [
            {data: 'name', name: 'name'},
            {data: 'instrument_id', name: 'instrument_id'},
            {data: 'tool_id', name: 'tool_id'},
            {data: 'description', name: 'description'},
            {data: 'type', name: 'type'},
            {data: 'entry', name: 'entry'}, 
            {data: 'max_value', name: 'max_value'},
            {data: 'min_value', name: 'min_value'},
            {data: 'engrineering_unit', name: 'engrineering_unit'},
            {data: 'created_at', name: 'created_at'},
            {data: 'action', name: 'action',  orderable: false, searchable: false},
        ]
    });


     var SITEURL = window.location+"/";
     $(document).ready( function () {
        $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
        });


        $('body').on('click', '#delete', function () {
            var parameter_id = $(this).data("id");
           
           if (confirm('Are you sure you want to delete this Parameter into the Database?')) {
     $.ajax({
                type: "get",
                url: SITEURL + "delete/"+parameter_id,
                success: function (data) {
                var oTable = $('.parameters-table').dataTable(); 
                oTable.fnDraw(false);
                $('#confirm_delete').show();
                $('#confirm_delete').fadeOut(5000,"swing");
                },
                error: function (data) {
                    console.log('Error:', data);
                    $('#foriegn_key_constraint').show();
                    $('#foriegn_key_constraint').fadeOut(5000,"swing");
                }
            });
        } else {
            
            //alert("Pagal hai phr delete pe click kue kiya tha ");
        }

     
           
        });

    });

     function showFunction(id)
    {
        //console.log("click : "+id)
        var url = SITEURL+id;
        window.open(url,'_self');
    }
    function editFunction(id)
    {
        //console.log("click : "+id)
        var url = SITEURL+id;
        window.open(url+"/edit",'_self');
    }
</script>
@stop

resources/views/datatables/qrcode-action-button.blade.php
<div class="row">
	
	<div class="col-md-6">
		<a href="javascript:void(0)" data-toggle="tooltip"  data-id="{{ $id }}" data-original-title="show" class="show"  onclick="showFunction('{{$id}}');">
		   <i class="far fa-eye" style="color: #201c3f"></i>
		</a>
	</div>

	<div class="col-md-6">
	<a href="javascript:void(0)" data-toggle="tooltip"  data-id="{{ $id }}" data-original-title="generate" class="generate"  onclick="GenerateQrcode('{{$id}}');">
		   <i class="far fa-qrcode" style="color: #02e8e8"></i>
		</a>
	</div>
</div>
 

resources/views/datatables/qrcode-datatable.blade.php
@section('datatable')
<table  class="table table-bordered table-striped table-condensed qrcode-table" style="width: 100%">
    <thead>
          <tr>
            <th>Instrument ID</th>
            <th>Name</th>
            <th>Description</th>
            <th>Timestamp</th>
            <th style="width: 9%">Action</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
@show

@section('css')

<link rel="stylesheet" type="text/css" href="{{ asset('vendor/datatables/css/dataTables.bootstrap4.min.css') }}">

@stop

@section('js')

<script type="text/javascript" src="{{ asset('vendor/datatables/js/dataTables.bootstrap4.min.js') }}"></script>

<script>
    var table = $('.qrcode-table').DataTable({
        processing: true,
        serverSide: true,
        scrollX: false,
        order: [ [3, 'desc'] ],
        ajax: "{{ route('qrcodes.index') }}",
        columns: [
            {data: 'department_id', name: 'department_id'},
            {data: 'name', name: 'name'},
            {data: 'description', name: 'description'},                
            {data: 'created_at', name: 'created_at'},
            {data: 'action', name: 'action',  orderable: false, searchable: false},
        ]
    });


     var SITEURL = window.location+"/";
     $(document).ready( function () {
        $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
        });


     //    $('body').on('click', '#delete', function () {
     //        var department_id = $(this).data("id");
           
     // //       if (confirm('Are you sure you want to delete this department into the database?')) {
     // // // $.ajax({
     // // //            type: "get",
     // // //            url: SITEURL + "delete/"+department_id,
     // // //            // success: function (data) {
     // // //            // var oTable = $('.qrcode-table').dataTable(); 
     // // //            // oTable.fnDraw(false);
     // // //            // },
     // // //            // error: function (data) {
     // // //            //     console.log('Error:', data);
     // // //            // }
     // // //        });
     // //        } 
     //        // else {
                
     //        //     alert("Pagal hai phr delete pe click kue kiya tha ");
     //        //         }
 
     
           
     //    });

    });

     function showFunction(id)
    {
        //console.log("click : "+id)
        var url = SITEURL+id;
        window.open("/qr-code",'_self');
    }
    function GenerateQrcode(id)
    {
        //console.log("click : "+id)
        var url = SITEURL+id;
        window.open(url+"/create",'_self');
    }
</script>
@stop

resources/views/datatables/role.blade.php
@section('datatable')
<center>
<div class="alert alert-success" style="display:none; width: 70%; text-align: center;" id="confirm_delete" role="alert"  >Role successfully deleted</div>

<div class="alert alert-warning" style="display:none; width: 70%; text-align: center;" id="foriegn_key_constraint" role="alert"  >Can not delete Role. This role is already in use</div>

</center>
<table  class="table table-bordered table-striped table-condensed  roles-table" style="width: 100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Timestamp</th>
                <th style="width: 9%">Action</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
@show

@section('css')

<link rel="stylesheet" type="text/css" href="{{ asset('vendor/datatables/css/dataTables.bootstrap4.min.css') }}">

@stop

@section('js')

<script type="text/javascript" src="{{ asset('vendor/datatables/js/dataTables.bootstrap4.min.js') }}"></script>

<script>
    var table = $('.roles-table').DataTable({
        processing: true,
        serverSide: true,
        scrollX: false,
        order: [ [1, 'desc'] ],
        ajax: "{{ route('roles.index') }}",
        columns: [
            {data: 'name', name: 'name'},
            {data: 'created_at', name: 'created_at'},
            {data: 'action', name: 'action'},
        ]
    });

   //var SITEURL = '{{URL::to("http://localhost/cbm/public/")}}';
   var SITEURL = window.location+"/";
     $(document).ready( function () {
        $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
    });

        $('body').on('click', '#delete', function () {
            var role_id = $(this).data("id");

            
            if (confirm("Are You sure want to delete !")) {
                $.ajax({
                    type: "get",
                    url: SITEURL + "delete/"+role_id,
                    success: function (data) {
                    var oTable = $('.roles-table').dataTable(); 
                    oTable.fnDraw(false);
                    $('#confirm_delete').show();
                    $('#confirm_delete').fadeOut(5000,"swing");
                    },
                    error: function (data) {
                    console.log('Error:', data);
                    $('#foriegn_key_constraint').show();
                    $('#foriegn_key_constraint').fadeOut(5000,"swing");
                    }
                });
            } else {
               
            }

        });
    
     });
   function showFunction(id)
    {
        //console.log("click : "+id)
        var url = SITEURL+id;
        window.open(url,'_self');
    }
    function editFunction(id)
    {
        //console.log("click : "+id)
        var url = SITEURL+id;
        window.open(url+"/edit",'_self');
    }
  </script>
@stop

resources/views/datatables/route-history-action-button-datatable.blade.php
<div class="row">
	<div class="col-md-4">
	</div>
	<div class="col-md-4">
		<a href="javascript:void(0)"  data-id="{{ $id }}"  onclick="showSkippedInstrument('{{$id}}');"><i class="fas fa-expand-arrows-alt"></i>
		</a>
	</div>
	<div class="col-md-4">
	</div>
</div>

 

resources/views/datatables/select-instrument-action-button.blade.php
<center>
	<div class="row">
		<div class="col-md-4">
			<a href="javascript:void(0)"   data-id="{{ $id }}" data-original-title="show" class="show"  onclick="showFunction('{{$id}}');">
			  <input type="checkbox" name="instruments[]" value="{{$id}}">
			</a>
		</div>
	</div>
</center>